version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

    networks:
      - local
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 --chdir /app/src main:app --workers 2 --max-requests 10000
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    ports:
      - "{{cookiecutter.flask_host}}:{{ cookiecutter.flask_port }}:{{ cookiecutter.flask_port }}"
    depends_on:
      - db
    networks:
      - local

networks:
  local:
    driver: bridge
